CREATE DATABASE IF NOT EXISTS pat_system;

USE pat_system;

CREATE TABLE IF NOT EXISTS roles (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
role_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
role_id BIGINT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT users_ibfk_1
FOREIGN KEY (role_id)
REFERENCES roles(id)
);

INSERT INTO roles (role_name) VALUES
('ADMIN'),
('HR'),
('STUDENT');
